on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.0-beta1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go test ./...
